---
- name: Install cloud-init packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: true
  vars:
    packages:
      - cloud-init
      - cloud-guest-utils
      - cloud-initramfs-copymods
      - cloud-initramfs-dyn-netconf
  when: ansible_os_family == "Debian"

- name: Install cloud-init packages
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - cloud-init
      - cloud-utils-growpart
  when: ansible_os_family == "RedHat"

